### PR TITLE
Clustering of files based on similarity scores.

### PR DESCRIPTION
**Pull request by RashmiNalwad**
Fixed clustering issue for edit_cosine_circle_packing.py.Data will be clustered based on the similarity scores.Same Issue is fixed for edit_cosine_cluster.py

### CODE REVIEW

**Comment by harsham05** [comment]
@RashmiNalwad This PR has conflicts, can you sync your fork and send a new PR?

**Comment by chrismattmann** [comment]
@RashmiNalwad please resolve conflicts and push so the PR is updated.

**Comment by AravindRam** [comment]
@chrismattmann 

Hi Professor,

I had written edit-cosine-circle-packing.py and  edit-cosine-cluster.py based on the JSON format which Circle Packing and Cluster-D3 expects. I had clustered based on the first value (x-coordinate present in the input csv file) and considered the similarity score to be size of the circle/cluster. But, you can also cluster based on the similarity score depending on the use-case. The use case which I considered only made sense if we clustered based on the x-coordinate or the y-coordinate. I would probably say to have a command line option for the user to decide on what basis the user wants to cluster so that all use cases are covered. 

If you want to cluster based on similarity score, you need to modify these 2 lines in edit-cosine-circle-packing.py 

[38](https://github.com/chrismattmann/tika-similarity/blob/master/edit-cosine-circle-packing.py#L38) and [48](https://github.com/chrismattmann/tika-similarity/blob/master/edit-cosine-circle-packing.py#L48) by changing cluster[0] to cluster[2]

Make a similar change in line number 38 and 48 for  edit-cosine-cluster.py as well.

**Comment by RashmiNalwad** [comment]
@AravindRam, yes I have made similar changes as in our use case clustering was to  be done on similarity scores  and even I think it will be better if we have an option to cluster based on x co-ordinate,y co-ordinate or similarity scores.

**Comment by chrismattmann** [comment]
Can you two collaborate and make it so it supports either

**Comment by chrismattmann** [comment]
@RashmiNalwad @AravindRam please collaborate and update the PR to seamlessly have an option to allow both approaches. Thanks and please send updated PR ASAP. Thanks.

**Comment by AravindRam** [comment]
Sure Professor @chrismattmann . Will make the changes and let you know soon.

**Comment by AravindRam** [comment]
Updated PR referenced in #69 pull request.

**Comment by RashmiNalwad** [comment]
Resolved in #69 PR.

**Comment by chrismattmann** [comment]
@RashmiNalwad can you submit a PR that adds your name as a contributor to README.md?

**Comment by RashmiNalwad** [comment]
Okay Professor @chrismattmann

**Pull request closed without merging**
