### PR TITLE
Added new computeScore for cosine_similarity.py and edit-value-similarity.py

### PR DESCRIPTION
**Pull request by aditya-n**
Added new functions to compute similarity scores in 'cosine_similarity.py' and 'edit-value-similarity.py'.
These compute similarity scores for each combination of rows in a single file.

### CODE REVIEW

**Comment by chrismattmann** [comment]
dear @aditya-n can you fix merge conflicts and then repush your local to update this PR?

**Comment by aditya-n** [comment]
@chrismattmann I've resolved the conflicts. Let me know if there is any other changes to be done.

**Comment by chrismattmann** [comment]
thank you @aditya-n i've committed it! welcome to OSS!

**Comment by aditya-n** [comment]
Awesome!! thanks.

**Pull request merged**
