### PR TITLE
Create edit-distance-visualization.py

### PR DESCRIPTION
**Pull request by AravindRam**
This is a python script to convert the csv file generated as an output from edit-distance.py and produce a JSON input to circle-packing D3 visualization.

### CODE REVIEW

**Comment by chrismattmann** [comment]
@harsham05 can you comment on this for improvements?

**Comment by AravindRam** [comment]
@chrismattmann @harsham05 
1) Renamed the file to edit-cosine-circle-packing.py
2) Added apache license.
3) Changed json filename to circle.json.

**Comment by chrismattmann** [comment]
thank you @AravindRam can you also update cluster-scores to read the CSV file as well so that we can generate clusters.json too?

**Comment by AravindRam** [comment]
@chrismattmann  : Sure Professor. I will generate and let you know.

**Comment by harsham05** [comment]
@AravindRam you are NOT leveraging the pairwise similarity scores to form clusters.

The D3 circle packing Viz doesnt seem to be viable in showcasing the same, as you are simply dumping the n(n-1)/2 pairwise scores document by document, into circles

cosine2
cosine1

**Comment by AravindRam** [comment]
@harsham05 : I had tried it on circlepacking.html and it worked properly. Let me check it on dynamic-circlepacking.html and get back to you.

**Comment by harsham05** [comment]
@AravindRam I see what your doing now

**Comment by AravindRam** [comment]
@harsham05 : I checked it on dynamic-circlepacking.html and found the issue is because of the long filenames present in the csv file. Basically, I am having the name of the cluster to be the unique name under x-coordinate column. Since, those filenames are long, the visualization looks cluttered. So, I have renamed the outer cluster names to be cluster0, cluster1 and so on just like how its done in the case of similarity.py. But, again when you zoom in by clicking on a particular cluster, the problem will still be there because the filename is read from the csv. What do you feel should be done then?
screen shot 2016-02-24 at 11 25 26 pm

**Comment by AravindRam** [comment]
@chrismattmann : The same python code can be used to generate json for clusters.json. I had run it on dynamic-cluster.html and this is a sample snapshot.

screen shot 2016-02-25 at 12 50 24 am

**Comment by harsham05** [comment]
Awesome work @AravindRam !

@chrismattmann This PR looks good to merge.

**Comment by AravindRam** [comment]
Thanks @harsham05

**Comment by chrismattmann** [comment]
Thanks @AravindRam merged! Can you add the code to generate clusters.json?? thanks please let me know.

**Comment by AravindRam** [comment]
@chrismattmann Thanks Professor! I have added the code to generate clusters.json as well and made a pull request.

**Pull request merged**
